branches:
  only:
    - master
language: ruby
rvm:
  - 2.4.0
before_install:
  - gem update --system
cache: bundler
services:
  - postgresql
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c "create database rails_ootb_test;" -U postgres
