branches:
  only:
    - master
language: ruby
rvm:
  - 2.4.0
  - 2.3
cache: bundler
services:
  - postgresql
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database rails-ootb_test;' -U postgres
