default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_ootb_development

test:
  <<: *default
  database: rails_ootb_test

production:
  <<: *default
  database: rails_ootb_production
  username: rails_ootb
  password: <%= ENV['RAILS-OOTB_DATABASE_PASSWORD'] %>
